# On every push this script is executed
on: push

name: Build and deploy GH Pages

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (to install dependencies like Bulma)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version to match your local environment

      # Step 3: Navigate to the theme directory and install dependencies
      - name: Install dependencies
        run: |
          cd themes/polymathic
          pnpm install

      # Step 4: Build and deploy using Zola
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.19.1
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          # Provide personal access token (use GITHUB_TOKEN for the same repo)
          TOKEN: ${{ secrets.TOKEN }}
